name: .NET

on:
  push:
    branches: [ master ]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  deploy-to-github-pages:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 8.0.x
    - name: get workload wasm
      run: dotnet workload install wasm-tools
      
    - name: Publish .NET Core Project
      run: dotnet publish
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      with:
          BRANCH: gh-pages
          FOLDER: .../../Capybara/bin/Release/net8.0/publish/wwwroot
